[profile.default]
src = "contracts"
out = "artifacts"
libs = ["node_modules"]
remappings = [
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
    "@uniswap/v4-core/=node_modules/@uniswap/v4-core/",
    "@uniswap/v4-periphery/=node_modules/@uniswap/v4-periphery/",
    "solmate/=node_modules/solmate/src/",
    "forge-std/=node_modules/@uniswap/v4-core/lib/forge-std/src/"
]

# Compilador
solc = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 1000000
via_ir = true

# RPC URLs
[rpc_endpoints]
base = "https://mainnet.base.org"
base_sepolia = "https://sepolia.base.org"

# Etherscan
[etherscan]
base = { key = "1DB36PUJRNG5KN22KFG82YQI8D4UUI2YYE" }

# Configuración de deployment
[profile.default.fuzz]
runs = 1000

[profile.default.invariant]
runs = 1000 